create table atender_dadiva (id int8 generated by default as identity, email varchar(255), nome varchar(255), telefone varchar(255), solicitardadiva_id int8, primary key (id));
create table avaliacao (id int8 generated by default as identity, avaliacoes varchar(255), nome varchar(255), tipo varchar(255), primary key (id));
create table criar_dadiva (id int8 generated by default as identity, dadiva varchar(255), email varchar(255), nome varchar(255), telefone varchar(255), primary key (id));
create table escolher_dadiva (id int8 generated by default as identity, email varchar(255), endereco varchar(255), ong varchar(255), telefone varchar(255), criardadiva_id int8, primary key (id));
create table solicitar_dadiva (id int8 generated by default as identity, dadiva varchar(255), email varchar(255), endereco varchar(255), ong varchar(255), telefone varchar(255), primary key (id));
create table usuario (user_id int4 generated by default as identity, email varchar(255), nome varchar(255), role varchar(255), senha varchar(255), primary key (user_id));
alter table if exists atender_dadiva add constraint FKrud8j2d4w1uk1fxg4g46kqygs foreign key (solicitardadiva_id) references solicitar_dadiva;
alter table if exists escolher_dadiva add constraint FK6yto96kbp1bj313nab329963r foreign key (criardadiva_id) references criar_dadiva;
